x1 = int(input("¿Cuál es el valor de x1? "))
y1 = int(input("¿Cuál es el valor de y1? "))
x2 = int(input("¿Cuál es el valor de x2? "))
y2 = int(input("¿Cuál es el valor de y2? "))
d = (((x2-x1)**2) + ((y2-y1)**2))**(1/2)
print ("La distacnia entre los puntos descritos es: %5.4f" % (d))
